name: cyclescape
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  card_swiper: ^3.0.1
  dio: ^5.3.3
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.4
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.6.1
  geolocator: ^10.1.0
  get: ^4.3.8
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  line_awesome_flutter: ^2.0.0
  location: ^5.0.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  smooth_page_indicator: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - assets/images/advertisement/
    - google_fonts/montserrat_alternates/
